# Part A:

In [1]:
#1. what is two to the power of five ?

x  = 2**5 #double * for power

print(x) #ans = 32

32


In [2]:
#2. create the vector for with following data points 23,27,25,45,67

y =  [23,27,25,45,67] #creating the list

print(y) #ans = [23, 27, 25, 45, 67]

[23, 27, 25, 45, 67]


In [3]:
#3. assign the name of vector

dict1 = { "monday" : 23,
         "tuesday" : 27,
         "wednesday": 25,
         "thursday" : 45,
         "friday" : 67
        } #creating a dictionary

print(dict1) #ans = {'monday': 23, 'tuesday': 27, 'wednesday': 25, 'thursday': 45, 'friday': 67}

{'monday': 23, 'tuesday': 27, 'wednesday': 25, 'thursday': 45, 'friday': 67}


In [4]:
#4. avarage of value in Q.2

avg = sum(y)/len(y) #where y = [23,27,25,45,67]

print(avg) #ans = 37.4

37.4


In [5]:
#5. find the day  when value was highest

for j,i in dict1.items():
    if max(dict1.values())==i:
        print(j) #ans = friday
    else:
        pass 

friday


# Part B:

In [6]:
#1. create function
def name(username):
    return "your name is : ",username
name(input("please enter the name:"))

please enter the name:


('your name is : ', '')

In [7]:
#2. two argument function

def countX(li, x):
    return li.count(x)
 
li = [9,5,6,9,3,9,5,6,2,9,3,7]
x = 9
print('{} has occurred {} times in "li".'.format(x, countX(li, x))) 

9 has occurred 4 times in "li".


In [8]:
#3. three value sum

def three_sum(a):
    count = 0
    for i in a: 
        if i%3==0:
            count = count+i #return 0 of number not divided by 3
    return count 
three_sum([3,6,1])

9

In [9]:
#4. prime number or not

def prime(n):
    if (n==1):
        return False
    elif (n==2):
        return True;
    else:
        for x in range(2,n):
            if(n % x==0):
                return False
            return True             
print(prime(3))

True


# Part C:

In [10]:
#1. rbind() and cbind()
import pandas as pd

In [11]:
df = pd.DataFrame({"A":[1,2,3]})

df1 = pd.DataFrame({"B":[4,5,6]})

rbind=pd.concat([df,df1],axis=0) # row bind

cbind = pd.concat([df,df1],axis=1) #column blind

In [12]:
rbind

A    B
0  1.0  NaN
1  2.0  NaN
2  3.0  NaN
0  NaN  4.0
1  NaN  5.0
2  NaN  6.0

In [13]:
cbind # cbind is the right option

A  B
0  1  4
1  2  5
2  3  6

In [14]:
#2.creating 5x5 metrix

import numpy as np # importing numpy module 
vector = np.array(range(1,26))
mat2 = vector.reshape(5,5)
print(mat2)
print(mat2.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)


In [15]:
#3. doing indexixg in mat2 array

print(mat2[1,1:3]) #n x m = low x column
print(mat2[2,1:3])

[7 8]
[12 13]


# Part D:

In [16]:
# dataset mtcars

#importong required library
import pandas as pd

# Import CSV mtcars
data = pd.read_csv('https://gist.githubusercontent.com/ZeccaLehn/4e06d2575eb9589dbe8c365d61cb056c/raw/64f1660f38ef523b2a1a13be77b002b98665cdfe/mtcars.csv')

# Edit element of column header
data.rename(columns={'Unnamed: 0':'brand'}, inplace=True)

In [17]:
#1. read 6 line of the data
data.head(6) 

brand   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   
5            Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2  
5     1

In [18]:
#2. finding mean of the data
data['carb'].mean()

2.8125

In [19]:
#3. select the row where all car has 6 cylinders
data[data['cyl']==6]

brand   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0        Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1    Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
3   Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
5          Valiant  18.1    6  225.0  105  2.76  3.460  20.22   1   0     3   
9         Merc 280  19.2    6  167.6  123  3.92  3.440  18.30   1   0     4   
10       Merc 280C  17.8    6  167.6  123  3.92  3.440  18.90   1   0     4   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.50   0   1     5   

    carb  
0      4  
1      4  
3      1  
5      1  
9      4  
10     4  
29     6

In [20]:
#4. select am, gear, carb

am_gear_carb = data[['am','gear','carb']]
am_gear_carb.head()

am  gear  carb
0   1     4     4
1   1     4     4
2   1     4     1
3   0     3     1
4   0     3     2

In [21]:
#5. creat performaced column
performance = data['performance']= data['hp']/data['wt']

In [22]:
data.head()

brand   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  performance  
0     4    41.984733  
1     4    38.260870  
2     1    40.086207  
3     1    34.214619  
4     2    50.872093

In [23]:
#6. mpg of Hornet Sportabout

data[data['brand']=='Hornet Sportabout'] #mpg of Hornet Sportabout 18.7

brand   mpg  cyl   disp   hp  drat    wt   qsec  vs  am  gear  \
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.44  17.02   0   0     3   

   carb  performance  
4     2    50.872093